version: '3'

services:

  todotests:
    image: todotests
    depends_on:
      - todobackend
      - todofrontend
    environment:
      - FRONT_HOST: todofrontend
    restart: always

  todofront:
    image: todofront
    ports:
      - 3000:3000
    depends_on:
      - todoback
    environment:
      - REACT_APP_API_HOST: todoback
    restart: always

  todoback:
    image: todoback
    ports:
      - 3001:3001
    restart: always

  
